/**
 * Easter-egg story for `secret`. Personality preserved, prose tightened.
 */
export const secret = {
  title: 'INCIDENT_REPORT_001.txt',
  body: [
    '~/secrets/INCIDENT_REPORT_001.txt',
    '─'.repeat(56),
    '',
    'CLASSIFIED // INTERNAL // 2023',
    '',
    'My very first job in tech was as a Centrix technician at',
    'Teleperformance, supporting engineers with monthly virtual',
    'machine updates for clients like AT&T and Starbucks.',
    '',
    'The work was steady. The downtime was generous.',
    '',
    'Curiosity took over.',
    '',
    'I started experimenting with remote desktop tooling and',
    'managed to chain my slow corporate workstation through to my',
    'personal PC at home. Then I went further — connecting from my',
    'laptop at school, to home, to work. A three-hop tunnel held',
    'together by youthful confidence.',
    '',
    'Technically: it worked beautifully.',
    '',
    'Operationally: it tripped a security alert. My access was',
    'revoked. Suspicious activity. I almost got fired.',
    '',
    "I didn't.",
    '',
    'But it became the first lesson I really *internalized* about',
    'system security, blast radius, and the difference between',
    '"can I?" and "should I?". Curiosity is a feature.',
    'Responsibility is what makes it shippable.',
    '',
    "It's also the reason I now run release management for a",
    "living. The kid who almost broke production grew up to",
    "protect it. Funny how that works.",
    '',
    '─'.repeat(56),
    'EOF',
  ],
};
